### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by luator** [MOCAP4ROS2-Project/mocap4ros2_vicon#13]
I just found this project but it's a bit unclear to me what the current status is.  Is it already usable?  If yes, is there some documentation somewhere?

**Comment by MFernandezCarmona** [comment]
Yes, it's usable.
Right now it's should be fully automated (i.e. just clone, get dependencies and compile as usual).
Anyway, as you may not be familiar with lifecycle nodes, I will let you know when the website tutorial is updated.
Just ask me  in the meantime, I might solve your questions as well.

**Comment by jpenaloza1211** [comment]
Hi, is this still an active project? Will any work on it continue sometime soon?

**Comment by MFernandezCarmona** [comment]
Hi,
It's maintained. I'm not actively working on it, but I'm trying to keep it usable. I'm updating install instructions right now. And, of course, contributions are welcome.
Best
