### ISSUE TITLE
CI and SDK sources

### ISSUE THREAD

**Issue by MFernandezCarmona** [MOCAP4ROS2-Project/mocap4ros2_vicon#9]
I just realised that in order to make vicon2_driver work on CI we need to it able to download the SDK sources on its own. I added a script that automates the SDK sources install into the package, but I don't know how to automate the sdk download and include the script into CMakeLists file. 
@fmrico @jmguerreroh  Ideas?

**Comment by fmrico** [comment]
Please, check how we did it these days in the `mocap4ros2_optitrack` repo.

**Comment by MFernandezCarmona** [comment]
Good, I see how you can embed an executable on a CMakeList file. Now I need to find the correct SDK download url. (Current one asks you to click "agree" and input your email)...

**Comment by aarsht7** [comment]
I dig it from the source. I was not sure which version you need.

Datastream SDK 1.11.0 : https://app.box.com/shared/static/xpmdwfsc79jim2sh7uvyysxbih3m7sft.zip

Datastream SDK 1.10.0 : https://app.box.com/shared/static/2bu5vcucz5bq5075f66sti6pfhwaxqt8.zip
 
Datastream SDK 1.9.0 : https://app.box.com/shared/static/e7930zn7cpcobhmotvb4o2crrmm38c43.zip
 
Datastream SDK 1.8.0 : https://app.box.com/shared/static/5efu89ktx9lvp2zdt5uba58ls88ayi8b.zip

Datastream SDK 1.7.1 : https://app.box.com/shared/static/dv76csc8sx36genw10jqhc58kkq08tw7.zip

**Comment by MFernandezCarmona** [comment]
Thanks @aarsht7, but we were trying to mimic with VICON what is done with OPTITRACK, so I don't need them by now.

In VICON, you have this URL https://www.vicon.com/software/datastream-sdk/?section=downloads 
My problem is that I can't find a download link, you have to type your email and click "download" manually.
And that's a problem for the CI.

Cheers

**Comment by aarsht7** [comment]
Hey @MFernandezCarmona 
Yes, I know that email and agreeing to terms thing. That's why I have dig into the source code of the website and found the following links associated with the different versions. I have provided you the direct download links just like optitrack ;)
Give it a try. Just click on any of the link above.

**Comment by MFernandezCarmona** [comment]
Wait ... that's **fantastic**! 
Thanks, I will add them to the script and CMakelist! Also, I need a coffee, I can't believe I didn't see your answer right in front of my eyes...

BTW, other people have forked the sdk, which is MIT licensed, but that would mean "another" repo to keep updated. I think @aarsht7 links will do the trick nicely (for linux at least).
